[WIP] Purge script for cleaning out old services from cachet
RedHatInsights/black-box-tester pull request #2
Opened 2019-12-18 21:40 UTC by thearifismail

Added script for cleaning out cachet

2019-12-20 14:37 UTC, kylape approved these changes
lgtm.  The only think I can see is that maybe you should check the status code coming from Cachet, but seeing that this is a first pass at a script, it's not a big deal.

2020-01-02 13:04 UTC, thearifismail commented
What does it mean by checking status code from Cachet?  Do you mean after deleting components and groups from Cachet, I should ask Cachet one last time, if it has any components or groups left?

2020-01-02 14:11 UTC, kylape commented
No, I mean check the HTTP response status code before reading the data from the response.

2020-01-02 20:25 UTC, kylape requested changes
If you're gonna add the check, please add it to all the requests.

2020-01-02 20:25 UTC, kylape commented on cachet-tools/purge-cachet.py
> +    if (response.status_code >= 200 and response.status_code <= 299):
I would invert the if clause, e.g. `if (response.status_code >= 300):` and then raise an exception or something.  That reduces the indention for all this code.  And you'll want to do the same thing for your other requests.

2020-01-02 20:25 UTC, kylape commented on cachet-tools/purge-cachet.py
> +                cdr = session.delete(URL + "/" + str(component['id']), verify=False, )
check it here

2020-01-02 20:25 UTC, kylape commented on cachet-tools/purge-cachet.py
> +                gdr = session.delete(URL + "/groups/" + str(group['id']), verify=False, )
check it here

2020-01-02 20:25 UTC, kylape commented on cachet-tools/purge-cachet.py
> +        response = session.get(URL, verify=False)
check it here

2020-01-02 20:25 UTC, kylape commented on cachet-tools/purge-cachet.py
> +            cdr = session.delete(URL + "/" + str(component['id']), verify=False, )
check it here

2020-01-02 20:39 UTC, thearifismail commented
> If you're gonna add the check, please add it to all the requests.

If I don't add the check what other solution you have in mind?

2020-01-02 21:42 UTC, kylape approved these changes

2020-01-02 21:42 UTC, merged